# Generated by Django 4.0.1 on 2022-01-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_note_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
